import type { Artifact } from "./types";

export function createReadme(projectName: string): Artifact {
  return {
    id: "artifact-readme",
    kind: "readme",
    title: "README.md",
    content: `# ${projectName}

AI resume optimization prototype generated by Multi-Agent Workspace.

## Run

\`\`\`bash
npm install
npm run dev
\`\`\`

## Features

- Paste resume text.
- Paste job description.
- Generate structured optimization suggestions.
- Review next iteration ideas.
`
  };
}

export function createArchitectureDoc(): Artifact {
  return {
    id: "artifact-architecture",
    kind: "architecture",
    title: "docs/architecture.md",
    content: `# Architecture

The prototype uses Vite, React, and TypeScript. The UI is intentionally local-first and can later connect to a model provider through a backend API.
`
  };
}

export function createNextSteps(): Artifact {
  return {
    id: "artifact-next-steps",
    kind: "next-steps",
    title: "Next Steps",
    content: [
      "1. Connect a real model provider through Model Gateway.",
      "2. Add persisted resume/project history.",
      "3. Add export to PDF or Markdown.",
      "4. Add team review workflow later."
    ].join("\n")
  };
}

